language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-openfin-generator' ]; then cd .. && eval "mv $currentfolder generator-openfin-generator" && cd generator-openfin-generator; fi

